import json
import sys

# Translations map for "text": "Russian Text": ("English Text", "Uzbek Text")
text_translations = {
    "BI-аналитик": ("BI Analyst", "BI tahlilchi"),
    "HR-аналитик": ("HR Analyst", "HR tahlilchi"),
    "PR-директор": ("PR Director", "PR direktori"),
    "UX/UI-дизайнер": ("UX/UI Designer", "UX/UI dizayneri"),
    "Администратор": ("Administrator", "Administrator"),
    "Администратор баз данных": ("Database Administrator", "Ma'lumotlar bazasi administratori"),
    "Администратор магазина": ("Store Administrator", "Do'kon administratori"),
    "Администратор проектов": ("Project Administrator", "Loyiha administratori"),
    "Аналитик 1С": ("1C Analyst", "1C tahlilchisi"),
    "Аналитик DWH": ("DWH Analyst", "DWH tahlilchisi"),
    "Аналитик данных": ("Data Analyst", "Ma'lumotlar tahlilchisi"),
    "Аналитик продаж": ("Sales Analyst", "Sotuv tahlilchisi"),
    "Арт-директор": ("Art Director", "Badiiy direktor"),
    "Архитектор-дизайнер": ("Architect-Designer", "Arxitektor-dizayner"),
    "Бармен": ("Bartender", "Barmen"),
    "Бизнес-аналитик": ("Business Analyst", "Biznes tahlilchi"),
    "Бухгалтер": ("Accountant", "Buxgalter"),
    "Бухгалтер на первичную документацию": ("Primary Documentation Accountant", "Boshlang'ich hujjatlar bo'yicha buxgalter"),
    "Бухгалтер на участок банк-клиент": ("Bank-Client Accountant", "Bank-mijoz bo'yicha buxgalter"),
    "Бухгалтер по расчету заработной платы": ("Payroll Accountant", "Ish haqi hisob-kitobi bo'yicha buxgalter"),
    "Бухгалтер по учету ТМЦ": ("Inventory Accountant", "TMZ hisobi bo'yicha buxgalter"),
    "Бухгалтер-кассир": ("Accountant-Cashier", "Buxgalter-kassir"),
    "Веб-аналитик": ("Web Analyst", "Veb-tahlilchi"),
    "Веб-дизайнер": ("Web Designer", "Veb-dizayner"),
    "Водитель": ("Driver", "Haydovchi"),
    "Врач акушер-гинеколог": ("Obstetrician-Gynecologist", "Akusher-ginekolog"),
    "Врач анестезиолог-реаниматолог": ("Anesthesiologist-Resuscitator", "Anesteziolog-reanimatolog"),
    "Врач клинической лабораторной диагностики": ("Clinical Laboratory Diagnostics Doctor", "Klinik laboratoriya diagnostikasi shifokori"),
    "Врач общей практики": ("General Practitioner", "Umumiy amaliyot shifokori"),
    "Врач травматолог-ортопед": ("Traumatologist-Orthopedist", "Travmatolog-ortoped"),
    "Врач ультразвуковой диагностики": ("Ultrasound Diagnostics Doctor", "Ultratovush diagnostikasi shifokori"),
    "Врач функциональной диагностики": ("Functional Diagnostics Doctor", "Funksional diagnostika shifokori"),
    "Врач-кардиолог": ("Cardiologist", "Kardiolog"),
    "Врач-методист/Медицинский статистик": ("Methodist Doctor/Medical Statistician", "Metodist shifokor/Tibbiy statistik"),
    "Врач-невролог": ("Neurologist", "Nevrolog"),
    "Врач-онколог": ("Oncologist", "Onkolog"),
    "Врач-оториноларинголог": ("Otorhinolaryngologist", "Otorinolaringolog (LOR)"),
    "Врач-офтальмолог": ("Ophthalmologist", "Oftalmolog"),
    "Врач-психиатр": ("Psychiatrist", "Psixiatr"),
    "Врач-рентгенолог": ("Radiologist", "Rentgenolog"),
    "Врач-терапевт": ("Therapist", "Terapevt"),
    "Врач-уролог": ("Urologist", "Urolog"),
    "Врач-физиотерапевт": ("Physiotherapist", "Fizioterapevt"),
    "Врач-хирург": ("Surgeon", "Xirurg"),
    "Врач-эндокринолог": ("Endocrinologist", "Endokrinolog"),
    "Гейм-дизайнер": ("Game Designer", "O'yin dizayneri"),
    "Главный бухгалтер": ("Chief Accountant", "Bosh buxgalter"),
    "Графический дизайнер": ("Graphic Designer", "Grafik dizayner"),
    "Грузчик": ("Loader", "Yuklovchi"),
    "Дизайнер интерьеров": ("Interior Designer", "Interyer dizayneri"),
    "Дизайнер мебели": ("Furniture Designer", "Mebel dizayneri"),
    "Дизайнер одежды": ("Fashion Designer", "Kiyim dizayneri"),
    "Дизайнер презентаций": ("Presentation Designer", "Taqdimot dizayneri"),
    "Дизайнер-верстальщик": ("Layout Designer", "Dizayner-sahifalo'vchi"),
    "Дизайнер-декоратор": ("Decorator Designer", "Dizayner-dekorator"),
    "Директор магазина": ("Store Manager", "Do'kon direktori"),
    "Директор медицинского центра": ("Medical Center Director", "Tibbiyot markazi direktori"),
    "Директор по информационным технологиям (CIO)": ("Chief Information Officer (CIO)", "Axborot texnologiyalari direktori (CIO)"),
    "Директор по качеству": ("Quality Director", "Sifat bo'yicha direktor"),
    "Директор по логистике": ("Logistics Director", "Logistika direktori"),
    "Директор по маркетингу": ("Marketing Director", "Marketing direktori"),
    "Директор по персоналу (HRD)": ("HR Director (HRD)", "Xodimlar bo'yicha direktor (HRD)"),
    "Директор по продукту": ("Product Director", "Mahsulot direktori"),
    "Директор ресторана": ("Restaurant Director", "Restoran direktori"),
    "Директор розничной сети": ("Retail Chain Director", "Chakana savdo tarmog'i direktori"),
    "Директор учебного заведения/заведующий учебным процессом": ("Educational Institution Director/Head of Educational Process", "Ta'lim muassasasi direktori/O'quv jarayoni mudiri"),
    "Директор филиала": ("Branch Director", "Filial direktori"),
    "Инвестиционный аналитик": ("Investment Analyst", "Investitsiya tahlilchisi"),
    "Инженер КИПиА": ("Instrumentation and Control Engineer", "Nazorat-o'lchov asboblari muhandisi"),
    "Инженер ПТО": ("Production and Technical Department Engineer", "PTO muhandisi"),
    "Инженер лесного хозяйства": ("Forestry Engineer", "O'rmon xo'jaligi muhandisi"),
    "Инженер по нагрузочному тестированию": ("Load Testing Engineer", "Yuklama sinovlari muhandisi"),
    "Инженер по охране труда и технике безопасности": ("Health and Safety Engineer", "Mehnat muhofazasi va xavfsizlik texnikasi muhandisi"),
    "Инженер по эксплуатации зданий и сооружений": ("Building Maintenance Engineer", "Bino va inshootlardan foydalanish muhandisi"),
    "Инженер путей сообщения": ("Railway Engineer", "Temir yo'l muhandisi"),
    "Инженер строительного контроля": ("Construction Control Engineer", "Qurilish nazorati muhandisi"),
    "Инженер-конструктор": ("Design Engineer", "Konstruktor-muhandis"),
    "Инженер-механик": ("Mechanical Engineer", "Mexanik-muhandis"),
    "Инженер-программист": ("Software Engineer", "Dasturchi-muhandis"),
    "Инженер-проектировщик": ("Design Engineer", "Loyiha muhandisi"),
    "Инженер-проектировщик ОВиК": ("HVAC Design Engineer", "HVAC loyiha muhandisi"),
    "Инженер-проектировщик систем электроснабжения": ("Power Supply Design Engineer", "Elektr ta'minoti tizimlari loyiha muhandisi"),
    "Инженер-проектировщик слаботочных систем": ("Low-Voltage Systems Design Engineer", "Kuchsiz oqim tizimlari loyiha muhandisi"),
    "Инженер-сметчик": ("Cost Engineer", "Smeta muhandisi"),
    "Инженер-химик": ("Chemical Engineer", "Kimyogar-muhandis"),
    "Инженер-эколог": ("Environmental Engineer", "Ekolog-muhandis"),
    "Инженер-электронщик": ("Electronics Engineer", "Elektronika muhandisi"),
    "Исполнительный директор (CEO)": ("Chief Executive Officer (CEO)", "Ijrochi direktor (CEO)"),
    "Кладовщик": ("Storekeeper", "Omborchi"),
    "Коммерческий директор (CCO)": ("Chief Commercial Officer (CCO)", "Tijorat direktori (CCO)"),
    "Коммуникационный дизайнер": ("Communication Designer", "Kommunikatsiya dizayneri"),
    "Комплектовщик": ("Picker", "Komplektlovchi"),
    "Копирайтер": ("Copywriter", "Kopirayter"),
    "Кочегар/Оператор котельной": ("Stoker/Boiler Operator", "Olovchi/Qozonxona operatori"),
    "Кредитный аналитик": ("Credit Analyst", "Kredit tahlilchisi"),
    "Курьер": ("Courier", "Kuryer"),
    "Ландшафтный архитектор": ("Landscape Architect", "Landshaft me'mori"),
    "Маркетинговый аналитик": ("Marketing Analyst", "Marketing tahlilchisi"),
    "Менеджер маркетплейсов": ("Marketplace Manager", "Marketpleys menejeri"),
    "Менеджер по ВЭД": ("Foreign Trade Manager", "Tashqi iqtisodiy faoliyat menejeri"),
    "Менеджер по внутренним коммуникациям": ("Internal Communications Manager", "Ichki kommunikatsiyalar menejeri"),
    "Менеджер по закупкам и снабжению": ("Procurement and Supply Manager", "Xaridlar va ta'minot menejeri"),
    "Менеджер по кадровому делопроизводству": ("HR Administration Manager", "Kadrlar ish yuritish menejeri"),
    "Менеджер по качеству": ("Quality Manager", "Sifat menejeri"),
    "Менеджер по логистике": ("Logistics Manager", "Logistika menejeri"),
    "Менеджер по маркетингу и PR": ("Marketing and PR Manager", "Marketing va PR menejeri"),
    "Менеджер по обучению и развитию персонала": ("L&D Manager", "Xodimlarni o'qitish va rivojlantirish menejeri"),
    "Менеджер по оптовым продажам": ("Wholesale Manager", "Ulgurji savdo menejeri"),
    "Менеджер по персоналу": ("HR Manager", "Xodimlar bo'yicha menejer"),
    "Менеджер по подбору персонала": ("Recruitment Manager", "Xodimlarni tanlash menejeri"),
    "Менеджер по продажам": ("Sales Manager", "Sotuv menejeri"),
    "Менеджер по работе с клиентами": ("Account Manager", "Mijozlar bilan ishlash menejeri"),
    "Менеджер по работе с ключевыми клиентами": ("Key Account Manager", "Muhim mijozlar bilan ishlash menejeri"),
    "Менеджер по работе с партнерами": ("Partnership Manager", "Hamkorlar bilan ishlash menejeri"),
    "Менеджер по транспортной логистике": ("Transport Logistics Manager", "Transport logistikasi menejeri"),
    "Менеджер по туризму": ("Tourism Manager", "Turizm menejeri"),
    "Менеджер продукта": ("Product Manager", "Mahsulot menejeri"),
    "Менеджер ресторана": ("Restaurant Manager", "Restoran menejeri"),
    "Мерчандайзер": ("Merchandiser", "Merchandayzer"),
    "Монтажник": ("Installer", "Montajchi"),
    "Моушн-дизайнер": ("Motion Designer", "Moushn-dizayner"),
    "Нарративный дизайнер": ("Narrative Designer", "Narrativ dizayner"),
    "Оператор call-центра": ("Call Center Operator", "Call-markaz operatori"),
    "Оператор ПК/Оператор базы данных": ("PC Operator/Database Operator", "EKM operatori/Ma'lumotlar bazasi operatori"),
    "Оператор аттракциона": ("Attraction Operator", "Attraksion operatori"),
    "Оператор почтовой связи": ("Postal Service Operator", "Pochta aloqasi operatori"),
    "Оператор производственной линии": ("Production Line Operator", "Ishlab chiqarish liniyasi operatori"),
    "Оператор станков с ЧПУ": ("CNC Machine Operator", "CHPU dastgohlari operatori"),
    "Оператор химчистки": ("Dry Cleaning Operator", "Kimyoviy tozalash operatori"),
    "Оператор-заправщик": ("Filling Station Attendant", "Operator-yoqilg'i quyuvchi"),
    "Операционный директор (COO)": ("Chief Operating Officer (COO)", "Operatsion direktor (COO)"),
    "Официант": ("Waiter", "Ofitsiant"),
    "Охранник": ("Security Guard", "Qo'riqchi"),
    "Полиграфический дизайнер": ("Print Designer", "Poligrafiya dizayneri"),
    "Помощник адвоката": ("Lawyer Assistant", "Advokat yordamchisi"),
    "Помощник нотариуса": ("Notary Assistant", "Notarius yordamchisi"),
    "Помощник повара": ("Assistant Cook", "Oshpaz yordamchisi"),
    "Помощник/ассистент руководителя": ("Executive Assistant", "Rahbar yordamchisi/Assistenti"),
    "Преподаватель": ("Teacher/Lecturer", "O'qituvchi"),
    "Продуктовый аналитик": ("Product Analyst", "Mahsulot tahlilchisi"),
    "Производственный директор / Технический директор": ("Production Director / Technical Director", "Ishlab chiqarish direktori / Texnik direktor"),
    "Промышленный дизайнер": ("Industrial Designer", "Sanoat dizayneri"),
    "Руководитель отдела аналитики": ("Head of Analytics", "Tahlil bo'limi rahbari"),
    "Сервисный инженер": ("Service Engineer", "Servis muhandisi"),
    "Сетевой администратор": ("Network Administrator", "Tarmoq administratori"),
    "Системный администратор": ("System Administrator", "Tizim administratori"),
    "Системный администратор Linux": ("Linux System Administrator", "Linux tizim administratori"),
    "Системный аналитик": ("System Analyst", "Tizim tahlilchisi"),
    "Судебный пристав по ОУПДС": ("Bailiff for OUPDS", "OUPDS bo'yicha sud ijrochisi"),
    "Судебный пристав-исполнитель": ("Bailiff-Executor", "Sud ijrochisi"),
    "Технический директор (CTO)": ("Chief Technology Officer (CTO)", "Texnik direktor (CTO)"),
    "Уборщик": ("Cleaner", "Tozalovchi"),
    "Финансовый аналитик": ("Financial Analyst", "Moliyaviy tahlilchi"),
    "Финансовый директор (CFO)": ("Chief Financial Officer (CFO)", "Moliyaviy direktor (CFO)"),
    "Экономист": ("Economist", "Iqtisodchi"),
    "Экспедитор": ("Forwarder", "Ekspeditor"),
    "Юрисконсульт": ("Legal Counsel", "Yuriskonsult"),
    "Юрист": ("Lawyer", "Yurist")
}

# Translations map for "professionalRoles.name": "Russian Name": ("English Name", "Uzbek Name")
role_translations = {
    "BI-аналитик, аналитик данных": ("BI Analyst, Data Analyst", "BI-tahlilchi, ma'lumotlar tahlilchisi"),
    "PR-менеджер": ("PR Manager", "PR-menejer"),
    "Администратор": ("Administrator", "Administrator"),
    "Администратор магазина, администратор торгового зала": ("Store Administrator, Floor Manager", "Do'kon administratori, savdo zali administratori"),
    "Аналитик": ("Analyst", "Tahlilchi"),
    "Арт-директор, креативный директор": ("Art Director, Creative Director", "Badiiy direktor, kreativ direktor"),
    "Архитектор": ("Architect", "Arxitektor"),
    "Бизнес-аналитик": ("Business Analyst", "Biznes tahlilchi"),
    "Бухгалтер": ("Accountant", "Buxgalter"),
    "Водитель": ("Driver", "Haydovchi"),
    "Врач": ("Doctor", "Shifokor"),
    "Гейм-дизайнер": ("Game Designer", "O'yin dizayneri"),
    "Генеральный директор, исполнительный директор (CEO)": ("General Director, Executive Director (CEO)", "Bosh direktor, ijrochi direktor (CEO)"),
    "Главный врач, заведующий отделением": ("Head Physician, Head of Department", "Bosh shifokor, bo'lim boshlig'i"),
    "Грузчик": ("Loader", "Yuklovchi"),
    "Дизайнер, художник": ("Designer, Artist", "Dizayner, rassom"),
    "Директор магазина, директор сети магазинов": ("Store Director, Retail Chain Director", "Do'kon direktori, do'konlar tarmog'i direktori"),
    "Директор по информационным технологиям (CIO)": ("Chief Information Officer (CIO)", "Axborot texnologiyalari direktori (CIO)"),
    "Директор по маркетингу и PR (CMO)": ("Marketing and PR Director (CMO)", "Marketing va PR direktori (CMO)"),
    "Директор по персоналу (HRD)": ("HR Director (HRD)", "Xodimlar bo'yicha direktor (HRD)"),
    "Другое": ("Other", "Boshqa"),
    "Инженер ПНР": ("Commissioning Engineer", "PNR muhandisi"),
    "Инженер ПТО, инженер-сметчик": ("Production and Technical Department Engineer, Cost Engineer", "PTO muhandisi, smeta muhandisi"),
    "Инженер по качеству": ("Quality Engineer", "Sifat muhandisi"),
    "Инженер по охране труда и технике безопасности, инженер-эколог": ("Health and Safety Engineer, Environmental Engineer", "Mehnat muhofazasi va xavfsizlik texnikasi muhandisi, ekolog-muhandis"),
    "Инженер по эксплуатации": ("Maintenance Engineer", "Foydalanish muhandisi"),
    "Инженер-конструктор, инженер-проектировщик": ("Design Engineer", "Konstruktor-muhandis, loyiha muhandisi"),
    "Инженер-электроник, инженер-электронщик": ("Electronics Engineer", "Elektronika muhandisi"),
    "Кладовщик": ("Storekeeper", "Omborchi"),
    "Коммерческий директор (CCO)": ("Chief Commercial Officer (CCO)", "Tijorat direktori (CCO)"),
    "Копирайтер, редактор, корректор": ("Copywriter, Editor, Proofreader", "Kopirayter, muharrir, musahhih"),
    "Кредитный специалист": ("Credit Specialist", "Kredit mutaxassisi"),
    "Курьер": ("Courier", "Kuryer"),
    "Маркетолог-аналитик": ("Marketing Analyst", "Marketolog-tahlilchi"),
    "Менеджер по закупкам": ("Procurement Manager", "Xarid menejeri"),
    "Менеджер по логистике, менеджер по ВЭД": ("Logistics Manager, Foreign Trade Manager", "Logistika menejeri, TIF menejeri"),
    "Менеджер по маркетингу, интернет-маркетолог": ("Marketing Manager, Internet Marketer", "Marketing menejeri, internet-marketolog"),
    "Менеджер по персоналу": ("HR Manager", "Xodimlar bo'yicha menejer"),
    "Менеджер по продажам, менеджер по работе с клиентами": ("Sales Manager, Account Manager", "Sotuv menejeri, mijozlar bilan ishlash menejeri"),
    "Менеджер по работе с партнерами": ("Partnership Manager", "Hamkorlar bilan ishlash menejeri"),
    "Менеджер по туризму": ("Tourism Manager", "Turizm menejeri"),
    "Менеджер продукта": ("Product Manager", "Mahsulot menejeri"),
    "Менеджер ресторана": ("Restaurant Manager", "Restoran menejeri"),
    "Мерчандайзер": ("Merchandiser", "Merchandayzer"),
    "Монтажник": ("Installer", "Montajchi"),
    "Начальник производства": ("Production Manager", "Ishlab chiqarish boshlig'i"),
    "Оператор call-центра, специалист контактного центра": ("Call Center Operator, Contact Center Specialist", "Call-markaz operatori, aloqa markazi mutaxassisi"),
    "Оператор ПК, оператор базы данных": ("PC Operator, Database Operator", "EKM operatori, ma'lumotlar bazasi operatori"),
    "Оператор производственной линии": ("Production Line Operator", "Ishlab chiqarish liniyasi operatori"),
    "Оператор станков с ЧПУ": ("CNC Machine Operator", "CHPU dastgohlari operatori"),
    "Операционный директор (COO)": ("Chief Operating Officer (COO)", "Operatsion direktor (COO)"),
    "Официант, бармен, бариста": ("Waiter, Bartender, Barista", "Ofitsiant, barmen, barista"),
    "Охранник": ("Security Guard", "Qo'riqchi"),
    "Повар, пекарь, кондитер": ("Cook, Baker, Confectioner", "Oshpaz, novvoy, qandolatchi"),
    "Программист, разработчик": ("Programmer, Developer", "Dasturchi, ishlab chiquvchi"),
    "Продуктовый аналитик": ("Product Analyst", "Mahsulot tahlilchisi"),
    "Разнорабочий": ("Handyman", "Yordamchi ishchi"),
    "Руководитель отдела аналитики": ("Head of Analytics", "Tahlil bo'limi rahbari"),
    "Руководитель отдела логистики": ("Head of Logistics", "Logistika bo'limi rahbari"),
    "Руководитель проектов": ("Project Manager", "Loyiha rahbari"),
    "Руководитель филиала": ("Branch Manager", "Filial rahbari"),
    "Секретарь, помощник руководителя, ассистент": ("Secretary, Executive Assistant, Assistant", "Kotib, rahbar yordamchisi, assistent"),
    "Сервисный инженер, инженер-механик": ("Service Engineer, Mechanical Engineer", "Servis muhandisi, mexanik-muhandis"),
    "Системный администратор": ("System Administrator", "Tizim administratori"),
    "Системный аналитик": ("System Analyst", "Tizim tahlilchisi"),
    "Специалист по кадрам": ("HR Specialist", "Kadrlar bo'yicha mutaxassis"),
    "Специалист по подбору персонала": ("Recruitment Specialist", "Xodimlarni tanlash bo'yicha mutaxassis"),
    "Тестировщик": ("Tester/QA", "Sinovchi/QA"),
    "Технический директор (CTO)": ("Chief Technology Officer (CTO)", "Texnik direktor (CTO)"),
    "Технолог": ("Technologist", "Texnolog"),
    "Уборщица, уборщик": ("Cleaner", "Farrosh"),
    "Упаковщик, комплектовщик": ("Packer, Picker", "Qadoqlovchi, komplektlovchi"),
    "Учитель, преподаватель, педагог": ("Teacher, Lecturer, Educator", "O'qituvchi, ma'ruza o'qituvchisi, pedagog"),
    "Финансовый аналитик, инвестиционный аналитик": ("Financial Analyst, Investment Analyst", "Moliyaviy tahlilchi, investitsiya tahlilchisi"),
    "Финансовый директор (CFO)": ("Chief Financial Officer (CFO)", "Moliyaviy direktor (CFO)"),
    "Экономист": ("Economist", "Iqtisodchi"),
    "Юрисконсульт": ("Legal Counsel", "Yuriskonsult"),
    "Юрист": ("Lawyer", "Yurist")
}

def process_item(item):
    if isinstance(item, dict):
        if "text" in item and item["text"] in text_translations:
            # Don't overwrite if manually set, but here we enforce consistency
            text_en, text_uz = text_translations[item["text"]]
            item["text_ru"] = item["text"]
            item["text_en"] = text_en
            item["text_uz"] = text_uz
        
        if "professionalRoles" in item and isinstance(item["professionalRoles"], list):
            for role in item["professionalRoles"]:
                if "name" in role and role["name"] in role_translations:
                    name_en, name_uz = role_translations[role["name"]]
                    role["name_ru"] = role["name"]
                    role["name_en"] = name_en
                    role["name_uz"] = name_uz

        for k, v in item.items():
            process_item(v)
    elif isinstance(item, list):
        for sub_item in item:
            process_item(sub_item)

def main():
    file_path = "backend/professions.json"
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        process_item(data)
        
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
        print("Successfully translated professions.json including professional roles")
    
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
