"""add_cascade_delete_to_favourites

Revision ID: 0f81a7d3d590
Revises: ef81c5f679eb
Create Date: 2026-02-01 12:26:37.775108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f81a7d3d590'
down_revision: Union[str, None] = 'ef81c5f679eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favourite_resumes_resume_id_fkey'), 'favourite_resumes', type_='foreignkey')
    op.drop_constraint(op.f('favourite_resumes_user_id_fkey'), 'favourite_resumes', type_='foreignkey')
    op.create_foreign_key(None, 'favourite_resumes', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favourite_resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('favourite_vacancies_user_id_fkey'), 'favourite_vacancies', type_='foreignkey')
    op.drop_constraint(op.f('favourite_vacancies_vacancy_id_fkey'), 'favourite_vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'favourite_vacancies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favourite_vacancies', 'vacancies', ['vacancy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourite_vacancies', type_='foreignkey')
    op.drop_constraint(None, 'favourite_vacancies', type_='foreignkey')
    op.create_foreign_key(op.f('favourite_vacancies_vacancy_id_fkey'), 'favourite_vacancies', 'vacancies', ['vacancy_id'], ['id'])
    op.create_foreign_key(op.f('favourite_vacancies_user_id_fkey'), 'favourite_vacancies', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'favourite_resumes', type_='foreignkey')
    op.drop_constraint(None, 'favourite_resumes', type_='foreignkey')
    op.create_foreign_key(op.f('favourite_resumes_user_id_fkey'), 'favourite_resumes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('favourite_resumes_resume_id_fkey'), 'favourite_resumes', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###
