"""field converting to str and max_length updated

Revision ID: 48269e5f4707
Revises: bb7dcb198dcc
Create Date: 2026-01-25 17:42:14.929935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48269e5f4707'
down_revision: Union[str, None] = 'bb7dcb198dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'photo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo_url',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.String(length=50),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
