"""empty message

Revision ID: 5501df961c2d
Revises: 863cdf81ecb4
Create Date: 2026-01-24 11:48:40.525916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5501df961c2d'
down_revision: Union[str, None] = '863cdf81ecb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profession_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Add column and foreign key in a SQLite-safe way using batch_alter_table
    if op.get_context().dialect.name == 'sqlite':
        with op.batch_alter_table('professions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_professions_category_id', 'profession_categories', ['category_id'], ['id'])
    else:
        op.add_column('professions', sa.Column('category_id', sa.Integer(), nullable=True))
        op.create_foreign_key('fk_professions_category_id', 'professions', 'profession_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key and column in a SQLite-safe way
    if op.get_context().dialect.name == 'sqlite':
        with op.batch_alter_table('professions', schema=None) as batch_op:
            batch_op.drop_constraint('fk_professions_category_id', type_='foreignkey')
            batch_op.drop_column('category_id')
    else:
        op.drop_constraint('fk_professions_category_id', 'professions', type_='foreignkey')
        op.drop_column('professions', 'category_id')
    op.drop_table('profession_categories')
    # ### end Alembic commands ###
