"""viewed count added

Revision ID: 791014be6c6c
Revises: ece4dfd8cdeb
Create Date: 2026-02-01 06:15:21.506779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791014be6c6c'
down_revision: Union[str, None] = 'ece4dfd8cdeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('viewed_count', sa.Integer(), default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'viewed_count')
    # ### end Alembic commands ###
