"""add is_active and is_admin fields

Revision ID: 863cdf81ecb4
Revises: a450211d0a9f
Create Date: 2026-01-23 04:31:40.795934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863cdf81ecb4'
down_revision: Union[str, None] = 'a450211d0a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('districts', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('professions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('regions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('regions', 'is_active')
    op.drop_column('professions', 'is_active')
    op.drop_column('districts', 'is_active')
    # ### end Alembic commands ###
