"""empty message

Revision ID: d53b05a7333a
Revises: b2c3d4e5f6a7
Create Date: 2026-05-02 09:01:59.642613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53b05a7333a'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('VACANCY', 'RESUME', name='channelmessageentity'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_messages_entity', 'channel_messages', ['entity_type', 'entity_id'], unique=False)
    # op.create_table('daily_job_seeker_districts',
    # sa.Column('daily_job_seeker_id', sa.Integer(), nullable=False),
    # sa.Column('district_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['daily_job_seeker_id'], ['daily_job_seekers.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('daily_job_seeker_id', 'district_id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('daily_job_seeker_districts')
    op.drop_index('ix_channel_messages_entity', table_name='channel_messages')
    op.drop_table('channel_messages')
    # ### end Alembic commands ###
