"""empty message

Revision ID: d61b5eb62a39
Revises: 0f81a7d3d590
Create Date: 2026-02-26 15:09:45.360505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61b5eb62a39'
down_revision: Union[str, None] = '0f81a7d3d590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('video', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'video')
    # ### end Alembic commands ###
