"""Add updated_at to models

Revision ID: ece4dfd8cdeb
Revises: 1db9f80618ed
Create Date: 2026-01-26 18:44:32.981308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece4dfd8cdeb'
down_revision: Union[str, None] = '1db9f80618ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite_resumes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('favourite_vacancies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vacancies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'updated_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('resumes', 'updated_at')
    op.drop_column('favourite_vacancies', 'updated_at')
    op.drop_column('favourite_resumes', 'updated_at')
    # ### end Alembic commands ###
