"""viewed count added as server_default value

Revision ID: ef81c5f679eb
Revises: 791014be6c6c
Create Date: 2026-02-01 06:43:46.314443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef81c5f679eb'
down_revision: Union[str, None] = '791014be6c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'viewed_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'viewed_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
